version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.3"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.16.3"
    ports:
      - "5601:5601"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      ELASTICSERCH_URL: http://elasticsearch:9200
    volumes:
      - grafana_data:/var/lib/grafana
  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.16.3"
    user: root
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - /var/lib/docker:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  grafana_data:
  elasticsearch_data:
